# NeoSMTPv2.5 Configuration. by Neocast Inc. 2001.5

# Directory
#Root_Dir=D:/backup/product/TSv20/TS4J/Queue_0
#Root_Dir=../Queue_0
Root_Dir=./Queue_0
# Foreign Host IP Address
DNS_Server_IP=168.126.63.1
Receive_Server_IP=172.30.1.39

# Local Port
SMTP_Port=2525
Interface_Port=10009
Mcast_Receive_Port=17019

# Foreign Port
Gen_Transfer_Port=22022
Merge_Transfer_Port=11011

# Send Config.
Active_Agent=20
Retry_Limit=2

# Virtual / Real Flag
Is_Real=true

Is_Standard=true

#������ ���� ���� ���� ���� �ð�
#0-23�� ���ڸ� �Է��Ѵ�.(DEFAULT ���� 1��)
GARBAGE_START_TIME = 1

#��߼� �ֱ�(1 : 1��)
RETRY_PERIOD=1

# TLS 관련 설정
# 적용 도메인, 도메인이 여러개일 경우 콤마(,)로 구분
TLS.target.domain=gmail.com, yahoo.co.kr
TLS.version=TLSv1.2